FROM tensorflow/tensorflow:1.3.0-py3

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ADD requirements-cpu.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]
